
import React, { useState } from 'react';
import { X, Download, FileJson, Code, Palette, Check, Hash, Copy, FileText } from 'lucide-react';
import { ThemeState, ProjectConfig } from '../types';

interface ExportModalProps {
    isOpen: boolean;
    onClose: () => void;
    theme: ThemeState;
    config: ProjectConfig;
    docs: any[];
    onToast: (msg: string, type: 'success' | 'error') => void;
}

export const ExportModal: React.FC<ExportModalProps> = ({
    isOpen,
    onClose,
    theme,
    config,
    docs,
    onToast
}) => {
    const [activeFormat, setActiveFormat] = useState<'json' | 'css' | 'tailwind' | 'specs'>('json');
    const [copied, setCopied] = useState(false);

    if (!isOpen) return null;

    const generateJSON = () => {
        const data = {
            id: Date.now().toString(),
            name: config.projectName || 'ZAP Project',
            timestamp: new Date().toISOString(),
            config,
            theme,
            docs
        };
        return JSON.stringify(data, null, 2);
    };

    const generateCSS = () => {
        return `:root {
  /* Brand Identity */
  --primary: ${theme.primary};
  --secondary: ${theme.secondary};
  --active-color: ${theme.activeColor || theme.primary};
  
  /* Backgrounds */
  --bg-main: ${theme.background};
  --bg-sub: ${theme.background2};
  --bg-input: ${theme.inputBg || '#FFFFFF'};
  
  /* Text Colors */
  --text-dark: ${theme.darkText};
  --text-gray: ${theme.grayText};
  --text-light: ${theme.lightText};
  
  /* UI Standard */
  --border-radius: ${theme.borderRadius}px;
  --input-border: ${theme.inputBorder || '#E5E7EB'};
  --form-ring: ${theme.formRingWidth || 4}px;
  --font-family: '${theme.fontFamily}', sans-serif;
  
  /* Buttons */
  --btn-padding-x: ${theme.btnPaddingX}px;
  --btn-padding-y: ${theme.btnPaddingY}px;
}`;
    };

    const generateTailwind = () => {
        return `module.exports = {
  theme: {
    extend: {
      colors: {
        brand: {
          primary: '${theme.primary}',
          secondary: '${theme.secondary}',
          active: '${theme.activeColor || theme.primary}',
        },
        surface: {
          main: '${theme.background}',
          sub: '${theme.background2}',
          input: '${theme.inputBg || '#FFFFFF'}',
        },
        content: {
          dark: '${theme.darkText}',
          gray: '${theme.grayText}',
          light: '${theme.lightText}',
        },
        status: {
          error: '${theme.formErrorColor || '#EF4444'}',
        }
      },
      borderRadius: {
        'brand': '${theme.borderRadius}px',
      },
      fontFamily: {
        'brand': ['${theme.fontFamily}', 'sans-serif'],
      }
    }
  }
}`;
    };

    const generateSpecs = () => {
        return `# Design Specifications: ${config.projectName}
        
## Brand Palette
- Primary: ${theme.primary}
- Secondary: ${theme.secondary}
- Background: ${theme.background}

## Typography
- Main Font: ${theme.fontFamily}
- Base Radius: ${theme.borderRadius}px

## Form Standard
- Variant: ${theme.formVariant || 'outlined'}
- Density: ${theme.formDensity || 'comfortable'}
- Input Padding: ${theme.inputPaddingX}px x ${theme.inputPaddingY}px

---
Generated by ZAP Design Engine - ${new Date().toLocaleDateString()}`;
    };

    const getActiveContent = () => {
        switch (activeFormat) {
            case 'json': return generateJSON();
            case 'css': return generateCSS();
            case 'tailwind': return generateTailwind();
            case 'specs': return generateSpecs();
            default: return '';
        }
    };

    const handleCopy = () => {
        navigator.clipboard.writeText(getActiveContent());
        setCopied(true);
        onToast('Copied to clipboard', 'success');
        setTimeout(() => setCopied(false), 2000);
    };

    const handleDownload = () => {
        const content = getActiveContent();
        const extensions = { json: 'json', css: 'css', tailwind: 'js', specs: 'md' };
        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        const fileName = (config.projectName || 'zap-design').toLowerCase().replace(/\s+/g, '-');
        a.href = url;
        a.download = `${fileName}-tokens.${extensions[activeFormat]}`;
        a.click();
        URL.revokeObjectURL(url);
        onToast('File downloaded successfully', 'success');
    };

    return (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-[200] flex items-center justify-center p-4 animate-in fade-in duration-300">
            <div className="bg-white w-full max-w-4xl rounded-[2.5rem] shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">

                {/* Header */}
                <div className="p-8 border-b border-gray-100 flex items-center justify-between bg-gray-50/50">
                    <div>
                        <h2 className="text-2xl font-black tracking-tight text-gray-900">Export Studio Assets</h2>
                        <p className="text-sm text-gray-500">Hand-off your design system tokens to developers.</p>
                    </div>
                    <button onClick={onClose} className="p-2 hover:bg-gray-200 rounded-full transition-colors">
                        <X size={24} className="text-gray-500" />
                    </button>
                </div>

                <div className="flex flex-1 overflow-hidden">
                    {/* Tabs Sidebar */}
                    <div className="w-56 border-r border-gray-100 p-4 bg-gray-50/30 space-y-2">
                        {[
                            { id: 'json', label: 'JSON State', icon: FileJson, desc: 'Re-import project' },
                            { id: 'css', label: 'CSS Variables', icon: Hash, desc: 'Web standard' },
                            { id: 'tailwind', label: 'Tailwind Config', icon: Code, desc: 'Modern styling' },
                            { id: 'specs', label: 'Brand Specs', icon: FileText, desc: 'Documentation' }
                        ].map(f => (
                            <button
                                key={f.id}
                                onClick={() => setActiveFormat(f.id as any)}
                                className={`w-full text-left p-3 rounded-2xl transition-all group ${activeFormat === f.id ? 'bg-white shadow-md' : 'hover:bg-gray-100'}`}
                            >
                                <div className="flex items-center gap-3 mb-1">
                                    <f.icon size={18} className={activeFormat === f.id ? 'text-purple-600' : 'text-gray-400'} />
                                    <span className={`text-xs font-bold ${activeFormat === f.id ? 'text-gray-900' : 'text-gray-500'}`}>{f.label}</span>
                                </div>
                                <p className="text-[10px] text-gray-400 pl-7">{f.desc}</p>
                            </button>
                        ))}
                    </div>

                    {/* Content Preview */}
                    <div className="flex-1 flex flex-col bg-slate-900 overflow-hidden relative">
                        <div className="absolute top-4 right-4 flex gap-2">
                            <button
                                onClick={handleCopy}
                                className="flex items-center gap-2 px-3 py-1.5 bg-white/10 hover:bg-white/20 text-white rounded-lg text-xs font-bold backdrop-blur-md transition-all border border-white/5"
                            >
                                {copied ? <Check size={14} className="text-green-400" /> : <Copy size={14} />}
                                {copied ? 'Copied' : 'Copy Code'}
                            </button>
                            <button
                                onClick={handleDownload}
                                className="flex items-center gap-2 px-3 py-1.5 bg-purple-600 hover:bg-purple-500 text-white rounded-lg text-xs font-bold shadow-lg transition-all"
                            >
                                <Download size={14} />
                                Download File
                            </button>
                        </div>

                        <div className="flex-1 p-8 overflow-auto custom-scrollbar">
                            <pre className="text-sm font-mono text-purple-300 whitespace-pre-wrap leading-relaxed">
                                {getActiveContent()}
                            </pre>
                        </div>

                        {/* Summary Footer */}
                        <div className="p-4 bg-black/40 border-t border-white/5 backdrop-blur-md flex items-center justify-between">
                            <div className="flex items-center gap-3">
                                <div className="w-8 h-8 rounded-lg overflow-hidden border border-white/10 flex items-center justify-center bg-white/5">
                                    <Palette size={16} style={{ color: theme.primary }} />
                                </div>
                                <div>
                                    <p className="text-[10px] uppercase font-black tracking-widest text-white/40">Active Brand</p>
                                    <p className="text-xs font-bold text-white/80">{config.projectName || 'Orbit Template'}</p>
                                </div>
                            </div>
                            <div className="text-right">
                                <p className="text-[10px] uppercase font-black tracking-widest text-white/40">Tokens Exported</p>
                                <p className="text-xs font-bold text-green-400">Production Ready</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};
